/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as privateErcSol from "./privateERC.sol";
export type { privateErcSol };
import type * as swapTokenSol from "./swapToken.sol";
export type { swapTokenSol };
export type { PrivateStorage } from "./PrivateStorage";
