/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as privateErcSol from "./privateERC.sol";
export * as swapTokenSol from "./swapToken.sol";
export { PrivateStorage__factory } from "./PrivateStorage__factory";
