/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cotiIo from "./@coti-io";
export type { cotiIo };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { IPrivateERC20 } from "./@coti-io/coti-contracts/contracts/token/PrivateERC20/IPrivateERC20";
export { IPrivateERC20__factory } from "./factories/@coti-io/coti-contracts/contracts/token/PrivateERC20/IPrivateERC20__factory";
export type { PrivateERC20 } from "./@coti-io/coti-contracts/contracts/token/PrivateERC20/PrivateERC20";
export { PrivateERC20__factory } from "./factories/@coti-io/coti-contracts/contracts/token/PrivateERC20/PrivateERC20__factory";
export type { MpcCore } from "./@coti-io/coti-contracts/contracts/utils/mpc/MpcCore";
export { MpcCore__factory } from "./factories/@coti-io/coti-contracts/contracts/utils/mpc/MpcCore__factory";
export type { ExtendedOperations } from "./@coti-io/coti-contracts/contracts/utils/mpc/MpcInterface.sol/ExtendedOperations";
export { ExtendedOperations__factory } from "./factories/@coti-io/coti-contracts/contracts/utils/mpc/MpcInterface.sol/ExtendedOperations__factory";
export type { MyPrivateToken } from "./contracts/privateERC.sol/MyPrivateToken";
export { MyPrivateToken__factory } from "./factories/contracts/privateERC.sol/MyPrivateToken__factory";
export type { PrivateStorage } from "./contracts/PrivateStorage";
export { PrivateStorage__factory } from "./factories/contracts/PrivateStorage__factory";
export type { PrivateSwap } from "./contracts/swapToken.sol/PrivateSwap";
export { PrivateSwap__factory } from "./factories/contracts/swapToken.sol/PrivateSwap__factory";
